server:
  port: 9002
  shutdown: graceful                    # 우아한 종료를 위한 활성화
  netty:
    connection-timeout: 2s              # 서버와 TCP 연결을 수립하기 위해 기다리는 시간
    idle-timeout: 15s                   # 데이터가 전송되지 않는 경우 TCP 연결을 닫기 전에 기다리는 시간

spring:
  application:
    name: cns-order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s     # 15초간의 우아한 종료기간을 둔다
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2s    # 풀에서 연결 객체 하나를 얻을 때까지 기다릴 수 있는 최대한의 시간
      initial-size: 5
      max-size: 10
  flyway:                               # 플라이웨이가 아직 R2DBC를 지원하지 않기 때문에 JDBC 드라이버를 통해 연결하도록 하기 위한 설정
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order

polar:
  catalog-service-uri: "http://localhost:9001"